# This file created by conda-build 26.3.0
# meta.yaml template originally from:
# D:\a\1\s\recipe, last modified Wed May  6 14:52:31 2026
# ------------------------------------------------

package:
  name: lcms2
  version: 2.19.1
source:
  url: https://github.com/mm2/Little-CMS/releases/download/lcms2.19.1/lcms2-2.19.1.tar.gz
  sha256: bfc54f7bab59fbc921012014a8032e4cba4abd46db47d46b76416a8c0b2815c8
  patches:
    - win_jpegturbo.patch
build:
  number: '0'
  run_exports:
    - lcms2 >=2.19.1,<3.0a0
  string: hf2c6c5f_0
requirements:
  build:
    - vs2022_win-64 19.44.35207 ha74f236_34
    - vs_win-64 2022.14 ha74f236_34
    - vswhere 3.1.7 h40126e0_1
  host:
    - lerc 4.1.0 hd936e49_0
    - libdeflate 1.25 h51727cc_0
    - libjpeg-turbo 3.1.4.1 hfd05255_0
    - liblzma 5.8.3 hfd05255_0
    - libtiff 4.7.1 h8f73337_1
    - libzlib 1.3.2 hfd05255_2
    - ucrt 10.0.26100.0 h57928b3_0
    - vc 14.3 h41ae7f8_34
    - vc14_runtime 14.44.35208 h818238b_34
    - vcomp14 14.44.35208 h818238b_34
    - zstd 1.5.7 h534d264_6
  run:
    - libjpeg-turbo >=3.1.4.1,<4.0a0
    - libtiff >=4.7.1,<4.8.0a0
    - ucrt >=10.0.20348.0
    - vc >=14.3,<15
    - vc14_runtime >=14.44.35208
test:
  commands:
    - jpgicc
    - tificc
    - linkicc
    - transicc
    - psicc
    - if not exist %LIBRARY_INC%\\lcms2.h exit 1
    - if not exist %LIBRARY_LIB%\\lcms2.lib exit 1
    - if not exist %LIBRARY_BIN%\\lcms2.dll exit 1
about:
  home: http://www.littlecms.com/
  license: MIT
  license_family: MIT
  license_file: LICENSE
  summary: Open Source Color Management Engine
extra:
  recipe-maintainers:
    - hmaarrfk
    - isuruf
  final: true
  copy_test_source_files: true
  flow_run_id: azure_20260506.2.1
  remote_url: https://github.com/conda-forge/lcms2-feedstock
  sha: 2c77b1d4adbc5ec3079e27889df91f2d2134afa6
